[versions]
# Plugins
agp = "8.13.1"
kotlin = "2.2.21"
junit5 = "1.14.0.0"

# AndroidX
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"

# Unit Test
junit = "4.13.2"
junitJupiterApi = "6.0.1"
androidTestCore = "1.9.0"

# Instrumentation Test
junitVersion = "1.3.0"
espressoCore = "3.7.0"

[libraries]
# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Unit Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterApi" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiterApi" }
android-test-core = { module = "de.mannodermaus.junit5:android-test-core", version.ref = "androidTestCore" }

# Instrumentation Test
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "junit5" }


